version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PLATFORM=linux/amd64,linux/arm64
        volumes:
            - .:/var/www/html
        ports:
            - "80:80"
            - "9000:9000"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - REDIS_HOST=redis
            - MEILISEARCH_HOST=http://meilisearch:7700
        depends_on:
            - db
            - redis
            - meilisearch

    db:
        image: mysql:8.0
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ludosport
            MYSQL_USER: ludosport
            MYSQL_PASSWORD: (C=&S}=H.]+0\g>6
        ports:
            - "3306:3306"

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin

    meilisearch:
        image: getmeili/meilisearch
        ports:
            - "7700:7700"

    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - prometheus_data:/prometheus

volumes:
    db_data:
    prometheus_data:
