global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "laravel_app"
    static_configs:
      - targets:
          - app:9000 # Porta FPM di default

  - job_name: "nginx"
    metrics_path: /metrics
    static_configs:
      - targets:
          - nginx-exporter:9113

  - job_name: "redis"
    static_configs:
      - targets:
          - redis-exporter:9121

  - job_name: "meilisearch"
    static_configs:
      - targets:
          - meilisearch:7700
    authorization:
      credentials: "${MEILISEARCH_KEY}"

  - job_name: "cadvisor"
    static_configs:
      - targets:
          - cadvisor:8080
